### ISSUE TITLE
Cleanup deprecated librdkafka functions

### ISSUE THREAD

**Issue by nick-zh** [php-rdkafka/php-rdkafka#248]
This is a ticket to track progress on deprecating or replacing deprecated librdkafka functions and providing their alternatives:

- [x] deprecate ` rd_kafka_errno` (#254)
- [x] deprecate `rd_kafka_errno2err` (#254)
- [x] replace internal `rd_kafka_errno2err` calls with  `rd_kafka_last_error()` (#252) 
- [x] deprecate `rd_kafka_set_log_level` (#251) 
- [x] deprecate `rd_kafka_set_logger` (#251) 
- [x] deprecate `rd_kafka_conf_set_default_topic_conf` (#266)
- [x] expose  `rd_kafka_conf_set_log_cb` (#253) (related issues #81, #127,#233)

**Comment by arnaud-lb** [comment]
+1.

Regarding `rd_kafka_last_error()`, we should probably not expose it, since we check it ourselves already (we throw exceptions in case of errors). We should replace `rd_kafka_errno2err(errno)` calls by `rd_kafka_last_error()` calls internally, though.

Regarding `rd_kafka_set_log_level()`, we should deprecated `Rdkafka::setLogLevel()` entirely (this method is the OO-equivalent of `rd_kafka_set_log_level()`).

Same for `rd_kafka_set_logger()`.

**Comment by nick-zh** [comment]
@arnaud-lb thanks for the feedback, i will try to implement the changes accordingly :+1:

**Comment by nick-zh** [comment]
@arnaud-lb is there a way to mark `rd_kafka_errno2err` and `rd_kafka_errno` as deprecated? I was unable to find if this is possible with `PHP_FE` since i was unable to find it in the internals doc :sweat_smile:

**Comment by arnaud-lb** [comment]
Yes, you can use `PHP_DEP_FE()`; it's an alias for `ZEND_DEP_FE()`: https://github.com/php/php-src/blob/php-7.3.7/Zend/zend_API.h#L74
